name: build WF
on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main

  workflow_dispatch:

  schedule:
    - cron: "10 14 * * 1_5" # after 14:10 every weekday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Maven build
        run: mvn install
  testing:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Code checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Run test on main branch
        run: mvn test

      - name: Checkstyle
        run: mvn checkstyle:checkstyle